### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ZenovJB** [HausemasterIssue/TickShift#10]
rename it to timer.java or tickshit.cpp

**Comment by HausemasterIssue** [comment]
tell me, what does tickshift achieve?

**Comment by ZenovJB** [comment]
> tell me, what does tickshift achieve?

wont tell what my tickshift does but ur timer is just timer thats it

**Comment by HausemasterIssue** [comment]
rofl you don't even know what its supposed to do LOL

**Comment by ZenovJB** [comment]
nice bait

**Comment by HausemasterIssue** [comment]
@ZenovJB who shit got rewritten now it works a million times better lol

**Comment by fuckyouthinkimboogieman** [comment]
зачем вы слили мое гуи((((((

![image](https://user-images.githubusercontent.com/43454376/140475380-58ad213d-c8ff-4cab-802e-193cd7419fb6.png)
