### ISSUE TITLE
doesnt even works lmao

### ISSUE THREAD

**Issue by ProfKambing** [HausemasterIssue/TickShift#2]
its just a timer 💀  ur not canceling any packets 💀 💀

**Comment by arjunnain17** [comment]
There needs to be a standing still check which he removed and also there is no packet cancelling required

**Comment by HausemasterIssue** [comment]
your standing still check is bad. you have to stay in one spot for like 3 seconds. i can achieve something very similar without it. i might add it later, if i do i will credit you fellas.

@ProfKambing thats kinda what tickshift is + the canceling packets isnt really necessary to achieve the same shit

**Comment by RealzPrestige** [comment]
LMAO U DONT KNOW WHAT TICKSHIFT IS IF UR CANCELLING NO PACKETD LOLLL

**Comment by HausemasterIssue** [comment]
@RealzPrestige who said i was done it?

**Comment by arjunnain17** [comment]
> your standing still check is bad. you have to stay in one spot for like 3 seconds. i can achieve something very similar without it. i might add it later, if i do i will credit you fellas.
> 
> @ProfKambing thats kinda what tickshift is + the canceling packets isnt really necessary to achieve the same shit

you haven't used a standing still check and also i dont think you understood out code
you need to stand still for "counter" amount of times to use timer for the next "counter" amount of time, ask doogie and he'll explain you , atleast that's what he explained to me and agrees with me.

Also , its okay to make mistakes but dont get your ego up its okay to make mistakes you need to accept that you wrote garbage which doesnt work (and called it a "fix" and "better")

**Comment by HausemasterIssue** [comment]
ok yes i admit it my code isnt perfect nor is it amazing, but it's a lot easier to read than you guys's. like, you guys write a for loop in one line, you need to use brackets on seperate lines lol. im sorry for calling your shit garbage. 

for starters your tickshift and my tickshift achieve a very similar thing, its the functionality that counts right? maybe i can make it better by taking other people's advice.

i understood the code i just got lost on the part of cancelling the movement packets. could you go into more detail on that?

also p.s. i can tell that last paragraph wasnt sincere 💀

**Comment by HausemasterIssue** [comment]
also ps ps. my code isnt "garbage" it just needs improving and it does work for me it just depends how you paste it

**Comment by arjunnain17** [comment]
Why don't you understand there needs to be a movement check to check whether the player has stood still for that amount of ticks , the way it works is that you need to stand still for "x" amount of ticks to use timer for the next "x amount of ticks and then out a limit for "x" , we implemented it correctly and flawlessly yet you decided to remove the check.

**Comment by noatmc** [comment]
chill

**Comment by HausemasterIssue** [comment]
yours dosent seem to autodisable. and human reaction time isnt really super
fast bro. also i can only move about the same distance with ur movement
check as i can without it.

**Comment by arjunnain17** [comment]
You seem to act monkey enough I should leave you alone holy

**Comment by HausemasterIssue** [comment]
well fuck we achieved nothing with everyone going on and on about how dumb
i am.

now nobody has a great tickshift and nobody is happy.

great job guys

**Comment by ProfKambing** [comment]
i have a good tickshift that actually shift ticks xD

**Comment by HausemasterIssue** [comment]
make a pr with it please

**Comment by ZenovJB** [comment]
> make a pr with it please

naw we aint leaking our shit

**Comment by HausemasterIssue** [comment]
i don't need your shit B)

**Comment by HausemasterIssue** [comment]
i rewrote it guys go look at it

**Comment by ProfKambing** [comment]
its still shit, cant spam it like ours,,

**Comment by HausemasterIssue** [comment]
fine with me. i made it myself and im happy with it lol. yours can stay
private, ill keep mine public and open source cuz private shit is CRINGE
idrc lol

**Comment by ProfKambing** [comment]
yea lmao cuz tickshift src isnt public

**Comment by HausemasterIssue** [comment]
the original tickshift is in future beta i believe and we dont have the src
to that so we have to rely on 0x22's explanation, if he even gave one + we
gotta remake it, we have no blueprint or idea to work off of, so dont be
mad that not everyones tickshift is INSANELY good

**Comment by ProfKambing** [comment]
our tickshift is spammable and almost 80% faster than yours

**Comment by HausemasterIssue** [comment]
@ProfKambing are you trying to make me feel like my hard work is shit lol?

**Comment by ProfKambing** [comment]
not your hardwork, thats a timer

**Comment by ProfKambing** [comment]
💀

**Comment by HausemasterIssue** [comment]
ITS A LOT FUCKING MORE THAN JUST A TIMER WITH AUTODISABLE BRO

IT HAS MOVEMENT CHECKS AND TICKS CAN YOU STOP TRYING TO SHIT ON MY WORK FOR THE LAST FUCKING TIME BRO?

IF YOUR SO SMART THEN GO RELEASE YOUR TIMER PUBLIC DOES THAT SOUND  GOOD TO YOU?

STOP CALLING ME SHIT IF YOURS ISNT EVEN PUBLIC U STUPID PUSSY

**Comment by ProfKambing** [comment]
rename it to timer this is very misleading

**Comment by ProfKambing** [comment]
ours shifts tick 🥶🥶🥶🥶

**Comment by ProfKambing** [comment]
hows that a hardwork its just a timer with some stuff that a 10 yo can do
