### ISSUE TITLE
👍 

### ISSUE THREAD

**Issue by noatmc** [HausemasterIssue/TickShift#3]
👍

**Comment by HausemasterIssue** [comment]
:3

**Comment by noatmc** [comment]
> :3
good job rewroting my shit btw, mine was a fixed chinese code cluster fuck so i don't mind anyone calling it chinese lol

**Comment by RealzPrestige** [comment]
Rewriting shitty useless timer disabler

**Comment by RealzPrestige** [comment]
that doesnt even work

**Comment by HausemasterIssue** [comment]
depends on how you skid it.
