### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by arjunnain17** [HausemasterIssue/TickShift#9]
"However, there are some disadvantages to using it. When you speed up the tick speed of the client, you are sending more packets at a faster rate. This can cause the anti-cheat of the server to rubberband or flag you if not done right. This means you can only turn this module on about every 6-ish seconds without getting rubberbanded. Of course the amount to wait will change depending on your settings."

You don't need to wait 120 ticks rofl we check for movement put the higher limit 16 ticks and we can pretty much use it after every 16ticks

**Comment by ZenovJB** [comment]
> "However, there are some disadvantages to using it. When you speed up the tick speed of the client, you are sending more packets at a faster rate. This can cause the anti-cheat of the server to rubberband or flag you if not done right. This means you can only turn this module on about every 6-ish seconds without getting rubberbanded. Of course the amount to wait will change depending on your settings."
> 
> You don't need to wait 120 ticks rofl we check for movement put the higher limit 16 ticks and we can pretty much use it after every 16ticks

nice timer.java dude

**Comment by HausemasterIssue** [comment]
@arjunnain17 add an autodisable to ur timer then come back here please
